services:
  db:
    image: postgres:16
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pMuwq41vsbjOXdtxqwkE3Asv9ID0Sqe9
      - POSTGRES_DB=db_name_ew2u
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'dslabdb:/var/lib/postgresql/data/'
  spring:
    image: sp
    build:
      context: .
      dockerfile: multistage.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d2vd6l75r7bs73cofibg-a.oregon-postgres.render.com:5432/db_name_ew2u
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pMuwq41vsbjOXdtxqwkE3Asv9ID0Sqe9
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3


volumes:
  dslabdb: