services:
  db:
    image: postgres:16
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=yQjbhRlOoGPCuoejHlJ4EK1KnEYdakfb
      - POSTGRES_DB=jdbc:postgresql://dpg-d0isj6je5dus739u94kg-a.oregon-postgres.render.com:5432/ds_project_db_ts3i
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'dslabdb:/var/lib/postgresql/data/'
  spring:
    image: sp
    build:
      context: .
      dockerfile: multistage.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d0isj6je5dus739u94kg-a.oregon-postgres.render.com:5432/ds_project_db_ts3i
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=yQjbhRlOoGPCuoejHlJ4EK1KnEYdakfb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3


volumes:
  dslabdb: