services:
  db:
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=aLvUzUkaU9nNK4MVEksMiCkkjFofBwp5
      - POSTGRES_DB=jdbc:postgresql://dpg-d187i2p5pdvs73bvc2ng-a.oregon-postgres.render.com:5432/dbname_ueiu
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'dslabdb:/var/lib/postgresql/data/'
  spring:
    image: sp
    build:
      context: .
      dockerfile: multistage.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d187i2p5pdvs73bvc2ng-a.oregon-postgres.render.com:5432/dbname_ueiu
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=aLvUzUkaU9nNK4MVEksMiCkkjFofBwp5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3


volumes:
  dslabdb: