apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring
  name: spring
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: spring